using GeoLeap.Api.Data;
using GeoLeap.Api.ProgrammaticSeo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using System.Text.RegularExpressions;
using Hangfire;

namespace GeoLeap.Api.ProgrammaticSeo.Services;

/// <summary>
/// Advanced SEO Page Generation Service with batch processing and intelligent optimization
/// </summary>
public class SeoPageGenerationService : ISeoPageGenerationService
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<SeoPageGenerationService> _logger;
    private readonly IDistributedCache _cache;
    private readonly IContentGenerationEngineService _contentGenerator;
    // Removed IAdvanced services that have been moved to separate modules
    // private readonly IAdvancedSeoTemplateService _templateService;
    // private readonly IAdvancedKeywordResearchService _keywordService;
    private readonly IContentQualityValidatorService _qualityValidator;
    private readonly IBackgroundJobClient _backgroundJobs;

    public SeoPageGenerationService(
        ApplicationDbContext context,
        ILogger<SeoPageGenerationService> logger,
        IDistributedCache cache,
        IContentGenerationEngineService contentGenerator,
        // IAdvancedSeoTemplateService templateService,
        // IAdvancedKeywordResearchService keywordService,
        IContentQualityValidatorService qualityValidator,
        IBackgroundJobClient backgroundJobs)
    {
        _context = context;
        _logger = logger;
        _cache = cache;
        _contentGenerator = contentGenerator;
        // _templateService = templateService;
        // _keywordService = keywordService;
        _qualityValidator = qualityValidator;
        _backgroundJobs = backgroundJobs;
    }

    public async Task<SeoPage> GeneratePageAsync(PageGenerationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Generating SEO page with template {TemplateId}", request.TemplateId);

            // Validate request
            var validationResult = await ValidateGenerationRequestAsync(request, cancellationToken);
            if (!validationResult.IsValid)
            {
                throw new InvalidOperationException($"Invalid generation request: {string.Join(", ", validationResult.Errors.Select(e => e.Message ?? "Unknown error"))}");
            }

            // Get template
            var template = await _context.Set<SeoTemplate>()
                .FirstOrDefaultAsync(t => t.Id == request.TemplateId, cancellationToken);

            if (template == null)
            {
                throw new InvalidOperationException($"Template not found: {request.TemplateId}");
            }

            // Generate content using content generation engine
            var generatedContent = await _contentGenerator.GenerateContentAsync(template, request.Variables, cancellationToken);

            // Create SEO page
            var page = new SeoPage
            {
                // Id will be auto-generated by database
                Title = request.Title ?? generatedContent.Title,
                Slug = request.Slug ?? GenerateSlug(request.Title ?? generatedContent.Title),
                Url = GenerateUrl(request.Slug ?? GenerateSlug(request.Title ?? generatedContent.Title)),
                MetaDescription = request.MetaDescription ?? generatedContent.MetaDescription,
                MetaKeywords = string.Join(", ", request.Keywords ?? new List<string>()),
                TemplateId = request.TemplateId,
                Status = request.Status,
                Content = generatedContent.Content,
                SchemaMarkup = generatedContent.SchemaMarkup,
                ContentVariablesDictionary = request.Variables,
                KeywordsList = (request.Keywords ?? new List<string>()).ToList(),
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
                PublishedAt = request.Status == SeoPageStatus.Published ? DateTime.UtcNow : null,
                SeoScore = generatedContent.QualityScore.SeoOptimizationScore,
                ReadabilityScore = generatedContent.QualityScore.ReadabilityScore,
                KeywordDensityScore = generatedContent.QualityScore.KeywordDensityScore,
                WordCount = CountWords(generatedContent.Content)
            };

            // Optimize for SEO if requested
            if (request.OptimizeForSeo)
            {
                page = await OptimizePageForSeo(page, request.Keywords?.ToList() ?? new List<string>());
            }

            // Add to database
            _context.Set<SeoPage>().Add(page);
            
            // Update template usage count
            template.UsageCount++;
            template.TotalPagesGenerated++;

            await _context.SaveChangesAsync(cancellationToken);

            // Publish immediately if requested
            if (request.PublishImmediately && page.Status == SeoPageStatus.Draft)
            {
                page.Status = SeoPageStatus.Published;
                page.PublishedAt = DateTime.UtcNow;
                await _context.SaveChangesAsync(cancellationToken);
            }

            _logger.LogInformation("Successfully generated SEO page {PageId} with title: {Title}", page.Id, page.Title);
            return page;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating SEO page with template {TemplateId}", request.TemplateId);
            throw new InvalidOperationException($"Page generation failed: {ex.Message}", ex);
        }
    }

    public async Task<BatchGenerationResult> GeneratePagesAsync(BatchGenerationRequest request, CancellationToken cancellationToken = default)
    {
        var startTime = DateTime.UtcNow;
        var generatedPages = new List<SeoPage>();
        var errors = new List<GenerationError>();

        try
        {
            _logger.LogInformation("Starting batch generation of {Count} pages with template {TemplateId}", 
                request.DataSets.Count(), request.TemplateId);

            var semaphore = new SemaphoreSlim(request.Options?.ConcurrencyLevel ?? Environment.ProcessorCount);
            var tasks = new List<Task>();

            foreach (var (dataSet, index) in request.DataSets.Select((ds, i) => (ds, i)))
            {
                tasks.Add(ProcessSinglePageGeneration(request, dataSet, index, generatedPages, errors, semaphore, cancellationToken));
                
                // Add delay between batches if specified
                if (request.Options?.DelayBetweenBatches > TimeSpan.Zero && index % request.BatchSize == 0 && index > 0)
                {
                    await Task.Delay(request.Options.DelayBetweenBatches, cancellationToken);
                }
            }

            await Task.WhenAll(tasks);

            var duration = DateTime.UtcNow - startTime;
            var metrics = CalculateBatchMetrics(generatedPages, duration);

            var result = new BatchGenerationResult
            {
                JobId = Guid.NewGuid().ToString(),
                TotalPages = request.DataSets.Count(),
                SuccessfulPages = generatedPages.Count,
                FailedPages = errors.Count,
                GeneratedPages = generatedPages,
                Errors = errors,
                Duration = duration,
                Metrics = metrics
            };

            _logger.LogInformation("Batch generation completed: {Successful}/{Total} pages generated in {Duration}", 
                result.SuccessfulPages, result.TotalPages, result.Duration);

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in batch page generation");
            throw new InvalidOperationException($"Batch generation failed: {ex.Message}", ex);
        }
    }

    public async Task<string> ScheduleBatchGenerationAsync(BatchGenerationRequest request, CancellationToken cancellationToken = default)
    {
        var jobId = Guid.NewGuid().ToString();

        // Create generation job record
        var generationJob = new SeoGenerationJob
        {
            Id = jobId,
            TemplateId = request.TemplateId.ToString(),
            Status = SeoJobStatus.Pending,
            BatchSize = request.DataSets.Count(),
            Priority = request.Priority,
            CreatedAt = DateTime.UtcNow,
            Configuration = JsonSerializer.Serialize(request)
        };

        _context.Set<SeoGenerationJob>().Add(generationJob);
        await _context.SaveChangesAsync(cancellationToken);

        // Schedule background job - convert to compatible type
        var seoRequest = new SeoBatchGenerationRequest
        {
            TemplateId = request.TemplateId,
            JobName = $"Batch Job {jobId}",
            BatchSize = request.DataSets.Count()
        };
        var backgroundJobId = _backgroundJobs.Enqueue<ISeoBackgroundJobService>(
            service => service.ScheduleBatchGenerationAsync(seoRequest));

        _logger.LogInformation("Scheduled batch generation job {JobId} with background job {BackgroundJobId}", 
            jobId, backgroundJobId);

        return jobId;
    }

    public async Task<GenerationJobStatus> GetGenerationStatusAsync(string jobId, CancellationToken cancellationToken = default)
    {
        var job = await _context.Set<SeoGenerationJob>()
            .FirstOrDefaultAsync(j => j.Id == jobId, cancellationToken);

        if (job == null)
        {
            throw new InvalidOperationException($"Generation job not found: {jobId}");
        }

        var estimatedRemaining = CalculateEstimatedTimeRemaining(job);

        return new GenerationJobStatus
        {
            JobId = jobId,
            Status = job.Status,
            Progress = job.Progress,
            TotalItems = job.BatchSize,
            ProcessedItems = job.ProcessedCount,
            SuccessfulItems = job.SuccessCount,
            FailedItems = job.ErrorCount,
            StartedAt = job.StartedAt,
            CompletedAt = job.CompletedAt,
            EstimatedRemaining = estimatedRemaining,
            ErrorMessages = job.ErrorMessages ?? new List<string>(),
            Metrics = new GenerationJobMetrics
            {
                CurrentThroughput = CalculateCurrentThroughput(job),
                AverageGenerationTime = CalculateAverageGenerationTime(job),
                MemoryUsage = GetCurrentMemoryUsage(),
                CpuUsage = GetCurrentCpuUsage()
            }
        };
    }

    public async Task<bool> CancelGenerationAsync(string jobId, CancellationToken cancellationToken = default)
    {
        var job = await _context.Set<SeoGenerationJob>()
            .FirstOrDefaultAsync(j => j.Id == jobId, cancellationToken);

        if (job == null || job.Status == SeoJobStatus.Completed || job.Status == SeoJobStatus.Failed)
        {
            return false;
        }

        job.Status = SeoJobStatus.Cancelled;
        job.CompletedAt = DateTime.UtcNow;

        await _context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Cancelled generation job {JobId}", jobId);
        return true;
    }

    public async Task<SeoPage> RegeneratePageAsync(string pageId, Dictionary<string, object>? newData = null, CancellationToken cancellationToken = default)
    {
        if (!long.TryParse(pageId, out var id))
        {
            throw new ArgumentException("Invalid page ID format", nameof(pageId));
        }
        
        var page = await _context.Set<SeoPage>()
            .Include(p => p.Template)
            .FirstOrDefaultAsync(p => p.Id == id, cancellationToken);

        if (page?.Template == null)
        {
            throw new InvalidOperationException($"Page or template not found: {pageId}");
        }

        // Use new data if provided, otherwise use existing data
        var variables = newData ?? page.ContentVariablesDictionary;

        // Generate new content
        var generatedContent = await _contentGenerator.GenerateContentAsync(page.Template, variables, cancellationToken);

        // Update page
        page.Content = generatedContent.Content;
        page.MetaDescription = generatedContent.MetaDescription;
        page.SchemaMarkup = generatedContent.SchemaMarkup;
        page.SeoScore = generatedContent.QualityScore.SeoOptimizationScore;
        page.ReadabilityScore = generatedContent.QualityScore.ReadabilityScore;
        page.KeywordDensityScore = generatedContent.QualityScore.KeywordDensityScore;
        page.WordCount = CountWords(generatedContent.Content);
        page.UpdatedAt = DateTime.UtcNow;

        if (newData != null)
        {
            page.ContentVariablesDictionary = newData;
        }

        await _context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Regenerated page {PageId}", pageId);
        return page;
    }

    public async Task<BulkRegenerationResult> RegeneratePagesAsync(IEnumerable<string> pageIds, RegenerationOptions? options = null, CancellationToken cancellationToken = default)
    {
        var startTime = DateTime.UtcNow;
        var updatedPages = new List<SeoPage>();
        var errors = new List<RegenerationError>();
        var skipped = 0;

        options ??= new RegenerationOptions();

        foreach (var pageId in pageIds)
        {
            try
            {
                var page = await RegeneratePageAsync(pageId, cancellationToken: cancellationToken);
                updatedPages.Add(page);
            }
            catch (InvalidOperationException)
            {
                skipped++;
            }
            catch (Exception ex)
            {
                errors.Add(new RegenerationError
                {
                    PageId = pageId,
                    Message = ex.Message,
                    Reason = "Regeneration failed",
                    IsRecoverable = true
                });
            }
        }

        return new BulkRegenerationResult
        {
            TotalPages = pageIds.Count(),
            RegeneratedPages = updatedPages.Count,
            SkippedPages = skipped,
            FailedPages = errors.Count,
            UpdatedPages = updatedPages,
            Errors = errors,
            Duration = DateTime.UtcNow - startTime
        };
    }

    public async Task<DataSourceGenerationResult> GenerateFromDataSourceAsync(DataSourceGenerationRequest request, CancellationToken cancellationToken = default)
    {
        var jobId = Guid.NewGuid().ToString();
        var startTime = DateTime.UtcNow;

        try
        {
            _logger.LogInformation("Starting data source generation with template {TemplateId} and source type {SourceType}", 
                request.TemplateId, request.DataSource.Type);

            // Retrieve data from source
            var data = await RetrieveDataFromSource(request.DataSource, request.Filters, cancellationToken);
            
            // Map data according to configuration
            var mappedData = await MapData(data, request.DataMapping, cancellationToken);

            // Filter data if needed
            if (request.Filters != null)
            {
                mappedData = ApplyDataFilters(mappedData, request.Filters);
            }

            // Convert to batch generation request
            var batchRequest = new BatchGenerationRequest
            {
                TemplateId = request.TemplateId,
                DataSets = mappedData,
                Options = request.Options,
                NotificationEmail = request.NotificationEmail
            };

            // Process generation
            var batchResult = await GeneratePagesAsync(batchRequest, cancellationToken);

            var metrics = new DataSourceMetrics
            {
                TotalRecordsRead = data.Count(),
                DataRetrievalTime = (DateTime.UtcNow - startTime).TotalSeconds,
                DataProcessingTime = batchResult.Duration.TotalSeconds,
                DuplicateRecords = CountDuplicates(data),
                InvalidRecords = data.Count() - mappedData.Count()
            };

            return new DataSourceGenerationResult
            {
                JobId = jobId,
                TotalRecords = data.Count(),
                ProcessedRecords = mappedData.Count(),
                GeneratedPages = batchResult.SuccessfulPages,
                SkippedRecords = data.Count() - mappedData.Count(),
                Errors = ConvertToDataProcessingErrors(batchResult.Errors),
                Metrics = metrics
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in data source generation");
            throw new InvalidOperationException($"Data source generation failed: {ex.Message}", ex);
        }
    }

    public async Task<GenerationValidationResult> ValidateGenerationRequestAsync(PageGenerationRequest request, CancellationToken cancellationToken = default)
    {
        var errors = new List<ValidationError>();
        var warnings = new List<ValidationWarning>();

        // Validate template exists
        var templateExists = await _context.Set<SeoTemplate>()
            .AnyAsync(t => t.Id == request.TemplateId && t.IsActive, cancellationToken);

        if (!templateExists)
        {
            errors.Add(new ValidationError
            {
                Code = "TEMPLATE_NOT_FOUND",
                Message = $"Template {request.TemplateId} not found or inactive"
            });
        }

        // Validate variables
        if (templateExists)
        {
            var template = await _context.Set<SeoTemplate>()
                .FirstAsync(t => t.Id == request.TemplateId, cancellationToken);

            var requiredVariables = template.VariablesList.Where(v => v.Required).Select(v => v.Name);
            foreach (var requiredVar in requiredVariables)
            {
                if (!request.Variables.ContainsKey(requiredVar))
                {
                    errors.Add(new ValidationError
                    {
                        Code = "MISSING_REQUIRED_VARIABLE",
                        Message = $"Required variable '{requiredVar}' is missing"
                    });
                }
            }
        }

        // Validate slug uniqueness if provided
        if (!string.IsNullOrEmpty(request.Slug))
        {
            var slugExists = await _context.Set<SeoPage>()
                .AnyAsync(p => p.Slug == request.Slug, cancellationToken);

            if (slugExists)
            {
                errors.Add(new ValidationError
                {
                    Code = "DUPLICATE_SLUG",
                    Message = $"Slug '{request.Slug}' already exists"
                });
            }
        }

        // Calculate complexity
        var complexity = CalculateGenerationComplexity(request);

        // Estimate resources
        var resourceEstimate = EstimateResources(request);

        return new GenerationValidationResult
        {
            IsValid = !errors.Any(),
            Errors = errors,
            Warnings = warnings,
            Complexity = complexity,
            ResourceEstimate = resourceEstimate
        };
    }

    public async Task<PageGenerationPreview> PreviewPageGenerationAsync(PageGenerationRequest request, CancellationToken cancellationToken = default)
    {
        // Validate request first
        var validation = await ValidateGenerationRequestAsync(request, cancellationToken);
        if (!validation.IsValid)
        {
            throw new InvalidOperationException($"Invalid request: {string.Join(", ", validation.Errors.Select(e => e.Message))}");
        }

        // Get template
        var template = await _context.Set<SeoTemplate>()
            .FirstOrDefaultAsync(t => t.Id == request.TemplateId, cancellationToken);

        if (template == null)
        {
            throw new InvalidOperationException($"Template not found: {request.TemplateId}");
        }

        // Process template to generate preview - TODO: Implement with ISeoPageGenerationService
        var processedTemplate = new GeoLeap.Api.ProgrammaticSeo.Models.ProcessedTemplate
        {
            Id = request.TemplateId,
            Name = template.Name,
            Type = template.Type,
            ProcessedContent = "Preview functionality moved to separate module",
            Variables = request.Variables,
            ProcessedAt = DateTime.UtcNow,
            ProcessingTime = TimeSpan.FromMilliseconds(100),
            ProcessedBy = "system",
            ContentLength = 100,
            VariableCount = request.Variables.Count,
            ProcessingSuccessful = true,
            Title = template.MetaTitle ?? template.Name,
            MetaDescription = template.MetaDescription ?? "",
            SchemaMarkup = "",
            QualityScore = 0.8
        };

        // Generate preview data
        var slug = request.Slug ?? GenerateSlug(request.Title ?? processedTemplate.Name);
        var url = GenerateUrl(slug);

        // Analyze SEO
        var seoAnalysis = await AnalyzeSeoForPreview(processedTemplate, request.Keywords?.ToList() ?? new List<string>());

        // Generate recommendations
        var recommendations = GeneratePreviewRecommendations(processedTemplate, seoAnalysis);

        return new PageGenerationPreview
        {
            PreviewHtml = processedTemplate.ProcessedContent,
            Title = request.Title ?? processedTemplate.Title,
            MetaDescription = request.MetaDescription ?? processedTemplate.MetaDescription,
            Keywords = string.Join(", ", request.Keywords ?? new List<string>()),
            SchemaMarkup = processedTemplate.SchemaMarkup,
            Slug = slug,
            Url = url,
            QualityScore = new ContentQualityScore { OverallScore = processedTemplate.QualityScore, ReadabilityScore = processedTemplate.QualityScore, SeoOptimizationScore = processedTemplate.QualityScore, KeywordDensityScore = processedTemplate.QualityScore },
            SeoAnalysis = seoAnalysis,
            Recommendations = recommendations
        };
    }

    public async Task<GenerationMetrics> GetGenerationMetricsAsync(TimeSpan? period = null, CancellationToken cancellationToken = default)
    {
        period ??= TimeSpan.FromDays(30);
        var startDate = DateTime.UtcNow.Subtract(period.Value);

        var pages = await _context.Set<SeoPage>()
            .Where(p => p.CreatedAt >= startDate)
            .Include(p => p.Template)
            .ToListAsync(cancellationToken);

        var totalPages = pages.Count;
        var todayPages = pages.Count(p => p.CreatedAt.Date == DateTime.UtcNow.Date);
        var weekPages = pages.Count(p => p.CreatedAt >= DateTime.UtcNow.AddDays(-7));
        var monthPages = pages.Count(p => p.CreatedAt >= DateTime.UtcNow.AddDays(-30));

        var trends = CalculateGenerationTrends(pages);
        var templateUsage = CalculateTemplateUsageMetrics(pages);
        var resourceUsage = await CalculateResourceUsage(period.Value);

        return new GenerationMetrics
        {
            TotalPagesGenerated = totalPages,
            PagesGeneratedToday = todayPages,
            PagesGeneratedThisWeek = weekPages,
            PagesGeneratedThisMonth = monthPages,
            AverageGenerationTime = CalculateAverageGenerationTime(pages),
            AverageQualityScore = pages.Any() ? pages.Average(p => p.SeoScore) : 0,
            SuccessRate = CalculateSuccessRate(pages),
            Trends = trends,
            TemplateUsage = templateUsage,
            ResourceUsage = resourceUsage
        };
    }

    public async Task<GenerationOptimizationResult> OptimizeGenerationSettingsAsync(string templateId, OptimizationCriteria criteria, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Optimizing generation settings for template {TemplateId}", templateId);
            
            if (!int.TryParse(templateId, out var id))
            {
                throw new ArgumentException("Invalid template ID format", nameof(templateId));
            }

            var template = await _context.Set<SeoTemplate>()
                .FirstOrDefaultAsync(t => t.Id == id, cancellationToken);

            if (template == null)
            {
                throw new InvalidOperationException($"Template not found: {templateId}");
            }

            // Analyze current performance
            var recentPages = await _context.Set<SeoPage>()
                .Where(p => p.TemplateId == id && p.CreatedAt >= DateTime.UtcNow.AddDays(-30))
                .ToListAsync(cancellationToken);

            // Generate optimized settings based on criteria
            var optimizedSettings = new GenerationSettings
            {
                ConcurrencyLevel = DetermineOptimalConcurrency(criteria),
                Timeout = DetermineOptimalTimeout(criteria),
                BatchSize = DetermineOptimalBatchSize(criteria),
                OptimizeForSpeed = criteria.OptimizationFocus == "speed",
                OptimizeForQuality = criteria.OptimizationFocus == "quality",
                QualityThresholds = new QualityThresholds
                {
                    MinSeoScore = criteria.TargetQualityScore,
                    MinReadabilityScore = Math.Max(60.0, criteria.TargetQualityScore - 10),
                    MinWordCount = criteria.MinWordCount,
                    MaxWordCount = criteria.MaxWordCount
                }
            };

            // Generate recommendations
            var recommendations = GenerateOptimizationRecommendations(template, recentPages, criteria);

            // Calculate predicted improvement
            var currentAvgScore = recentPages.Any() ? recentPages.Average(p => p.SeoScore) : 50.0;
            var predictedImprovement = Math.Min(criteria.TargetQualityScore - currentAvgScore, 25.0);

            var metrics = new OptimizationMetrics
            {
                PerformanceScore = currentAvgScore,
                SeoScore = criteria.TargetQualityScore,
                ContentQualityScore = predictedImprovement,
                TechnicalScore = recentPages.Count,
                AnalyzedAt = DateTime.UtcNow,
                TargetEntity = "template",
                EntityId = templateId
            };

            return new GenerationOptimizationResult
            {
                TemplateId = id,
                OptimizedSettings = optimizedSettings,
                Recommendations = recommendations,
                PredictedImprovement = predictedImprovement,
                Metrics = metrics
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error optimizing generation settings for template {TemplateId}", templateId);
            throw new InvalidOperationException($"Optimization failed: {ex.Message}", ex);
        }
    }

    public async Task<PageExportResult> ExportPagesAsync(PageExportRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Exporting pages with format {Format}", request.Format);

            var query = _context.Set<SeoPage>().AsQueryable();

            // Apply filters
            if (request.PageIds?.Any() == true)
            {
                query = query.Where(p => request.PageIds.Contains(p.Id));
            }

            if (request.Filter != null)
            {
                query = ApplyExportFilters(query, request.Filter);
            }

            var pages = await query.ToListAsync(cancellationToken);

            // Prepare export data
            var exportData = pages.Select(p => new
            {
                Id = p.Id,
                Title = p.Title,
                Slug = p.Slug,
                Url = p.Url,
                Content = request.IncludeContent ? p.Content : null,
                MetaDescription = p.MetaDescription,
                MetaKeywords = p.MetaKeywords,
                Status = p.Status.ToString(),
                CreatedAt = p.CreatedAt,
                UpdatedAt = p.UpdatedAt,
                PublishedAt = p.PublishedAt,
                SeoScore = p.SeoScore,
                WordCount = p.WordCount,
                Metadata = request.IncludeMetadata ? new
                {
                    TemplateId = p.TemplateId,
                    Category = p.Category,
                    Author = p.Author,
                    Variables = p.ContentVariablesDictionary,
                    Keywords = p.KeywordsList
                } : null,
                PerformanceData = request.IncludePerformanceData ? new
                {
                    SeoScore = p.SeoScore,
                    ReadabilityScore = p.ReadabilityScore,
                    KeywordDensityScore = p.KeywordDensityScore
                } : null
            });

            // Generate export content based on format
            byte[] data;
            string contentType;
            string fileName = request.FileName ?? $"pages-export-{DateTime.UtcNow:yyyyMMdd-HHmmss}";

            switch (request.Format)
            {
                case Models.ExportFormat.Json:
                    var json = JsonSerializer.Serialize(exportData, new JsonSerializerOptions { WriteIndented = true });
                    data = System.Text.Encoding.UTF8.GetBytes(json);
                    contentType = "application/json";
                    fileName += ".json";
                    break;

                case Models.ExportFormat.Csv:
                    var csv = ConvertToCsv(exportData);
                    data = System.Text.Encoding.UTF8.GetBytes(csv);
                    contentType = "text/csv";
                    fileName += ".csv";
                    break;

                case Models.ExportFormat.Xml:
                    var xml = ConvertToXml(exportData);
                    data = System.Text.Encoding.UTF8.GetBytes(xml);
                    contentType = "application/xml";
                    fileName += ".xml";
                    break;

                default:
                    throw new NotSupportedException($"Export format {request.Format} is not supported");
            }

            // Apply compression if requested
            if (request.Compression != CompressionFormat.None)
            {
                data = ApplyCompression(data, request.Compression);
                fileName += GetCompressionExtension(request.Compression);
            }

            var metadata = new ExportMetadata
            {
                ExportedAt = DateTime.UtcNow,
                ExportedBy = "system",
                Version = "1.0",
                FileSize = data.Length
            };

            return new PageExportResult
            {
                FileName = fileName,
                ContentType = contentType,
                Data = data,
                ExportedPagesCount = pages.Count,
                Metadata = metadata
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error exporting pages");
            throw new InvalidOperationException($"Export failed: {ex.Message}", ex);
        }
    }

    public async Task<PageImportResult> ImportPagesAsync(PageImportRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Importing pages from {FileName} with format {Format}", request.FileName, request.Format);

            var importedPages = new List<SeoPage>();
            var errors = new List<ImportError>();
            var skipped = 0;

            // Parse import data based on format
            var importData = ParseImportData(request.Data, request.Format);

            foreach (var (item, index) in importData.Select((item, i) => (item, i)))
            {
                try
                {
                    if (request.ValidateBeforeImport)
                    {
                        var validationErrors = ValidateImportItem(item);
                        if (validationErrors.Any())
                        {
                            errors.AddRange(validationErrors.Select(e => new ImportError
                            {
                                LineNumber = index + 1,
                                ErrorType = "Validation",
                                Message = e
                            }));
                            continue;
                        }
                    }

                    // Check for existing page
                    var existingPage = await _context.Set<SeoPage>()
                        .FirstOrDefaultAsync(p => p.Slug == item.Slug || p.Id.ToString() == item.Id, cancellationToken);

                    if (existingPage != null && !request.OverwriteExisting)
                    {
                        skipped++;
                        continue;
                    }

                    // Create or update page
                    var page = existingPage ?? new SeoPage { Id = !string.IsNullOrEmpty(item.Id) && long.TryParse(item.Id, out var parsedId) ? parsedId : 0 };

                    page.Title = item.Title;
                    page.Slug = item.Slug;
                    page.Url = item.Url ?? GenerateUrl(item.Slug);
                    page.Content = item.Content;
                    page.MetaDescription = item.MetaDescription;
                    page.MetaKeywords = item.MetaKeywords;
                    page.TemplateId = !string.IsNullOrEmpty(item.TemplateId) && int.TryParse(item.TemplateId, out var templateId) ? templateId : (!string.IsNullOrEmpty(request.DefaultTemplate) && int.TryParse(request.DefaultTemplate, out var defaultTemplateId) ? defaultTemplateId : 0);
                    page.Status = Enum.TryParse<SeoPageStatus>(item.Status, out var status) ? status : SeoPageStatus.Draft;
                    page.UpdatedAt = DateTime.UtcNow;

                    if (existingPage == null)
                    {
                        page.CreatedAt = item.CreatedAt ?? DateTime.UtcNow;
                        _context.Set<SeoPage>().Add(page);
                    }

                    importedPages.Add(page);
                }
                catch (Exception ex)
                {
                    errors.Add(new ImportError
                    {
                        LineNumber = index + 1,
                        ErrorType = "Processing",
                        Message = ex.Message
                    });
                }
            }

            await _context.SaveChangesAsync(cancellationToken);

            var metadata = new ImportMetadata
            {
                ImportedAt = DateTime.UtcNow,
                SourceFileName = request.FileName,
                OriginalFileSize = request.Data.Length,
                ProcessingTime = TimeSpan.FromSeconds(1) // Simplified
            };

            return new PageImportResult
            {
                TotalPages = importData.Count(),
                ImportedPages = importedPages.Count,
                SkippedPages = skipped,
                FailedPages = errors.Count,
                ImportedPagesList = importedPages,
                Errors = errors,
                Metadata = metadata
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error importing pages");
            throw new InvalidOperationException($"Import failed: {ex.Message}", ex);
        }
    }

    public async Task<BulkOperationResult> ArchivePagesAsync(IEnumerable<string> pageIds, bool permanent = false, CancellationToken cancellationToken = default)
    {
        var startTime = DateTime.UtcNow;
        var errors = new List<BulkOperationError>();
        var successCount = 0;

        try
        {
            _logger.LogInformation("Archiving {Count} pages (permanent: {Permanent})", pageIds.Count(), permanent);

            foreach (var pageId in pageIds)
            {
                try
                {
                    var page = await _context.Set<SeoPage>()
                        .FirstOrDefaultAsync(p => p.Id.ToString() == pageId, cancellationToken);

                    if (page == null)
                    {
                        errors.Add(new BulkOperationError
                        {
                            PageId = pageId,
                            Operation = "Archive",
                            ErrorMessage = "Page not found",
                            IsRetryable = false
                        });
                        continue;
                    }

                    if (permanent)
                    {
                        _context.Set<SeoPage>().Remove(page);
                    }
                    else
                    {
                        page.Status = SeoPageStatus.Archived;
                        page.UpdatedAt = DateTime.UtcNow;
                    }

                    successCount++;
                }
                catch (Exception ex)
                {
                    errors.Add(new BulkOperationError
                    {
                        PageId = pageId,
                        Operation = "Archive",
                        ErrorMessage = ex.Message,
                        IsRetryable = true
                    });
                }
            }

            await _context.SaveChangesAsync(cancellationToken);

            return new BulkOperationResult
            {
                TotalPages = pageIds.Count(),
                SuccessfulOperations = successCount,
                FailedOperations = errors.Count,
                Errors = errors,
                Duration = DateTime.UtcNow - startTime
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in bulk archive operation");
            throw new InvalidOperationException($"Bulk archive failed: {ex.Message}", ex);
        }
    }

    public async Task<SitemapGenerationResult> GenerateSitemapAsync(SitemapGenerationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Generating sitemap with format {Format}", request.Format);

            var query = _context.Set<SeoPage>()
                .Where(p => p.Status == SeoPageStatus.Published);

            // Apply filters
            if (request.PageIds?.Any() == true)
            {
                query = query.Where(p => request.PageIds.Contains(p.Id));
            }

            if (request.Filter != null)
            {
                query = ApplySitemapFilters(query, request.Filter);
            }

            var pages = await query
                .Take(request.MaxUrls)
                .OrderByDescending(p => p.UpdatedAt)
                .ToListAsync(cancellationToken);

            string sitemapContent;
            string fileName;

            switch (request.Format)
            {
                case SitemapFormat.Xml:
                    sitemapContent = GenerateXmlSitemap(pages, request);
                    fileName = "sitemap.xml";
                    break;

                case SitemapFormat.Text:
                    sitemapContent = GenerateTextSitemap(pages, request);
                    fileName = "sitemap.txt";
                    break;

                default:
                    throw new NotSupportedException($"Sitemap format {request.Format} is not supported");
            }

            var metadata = new SitemapMetadata
            {
                GeneratedAt = DateTime.UtcNow,
                TotalUrls = pages.Count,
                ImageUrls = request.IncludeImages ? CountImageUrls(pages) : 0,
                VideoUrls = request.IncludeVideos ? CountVideoUrls(pages) : 0
            };

            return new SitemapGenerationResult
            {
                SitemapContent = sitemapContent,
                FileName = fileName,
                IncludedUrls = pages.Count,
                ExcludedUrls = Math.Max(0, await query.CountAsync(cancellationToken) - pages.Count),
                GeneratedAt = DateTime.UtcNow,
                Metadata = metadata
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating sitemap");
            throw new InvalidOperationException($"Sitemap generation failed: {ex.Message}", ex);
        }
    }

    public async Task<SchemaMarkupResult> GenerateSchemaMarkupAsync(SchemaGenerationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Generating schema markup for {Count} pages", request.PageIds.Count());

            var pages = await _context.Set<SeoPage>()
                .Where(p => request.PageIds.Contains(p.Id))
                .ToListAsync(cancellationToken);

            var pageSchemas = new Dictionary<string, string>();
            var validationErrors = new List<SchemaValidationError>();
            var schemaTypeCounts = new Dictionary<string, int>();

            foreach (var page in pages)
            {
                try
                {
                    var schema = await GenerateSchemaForPage(page, request.SchemaType, request.Format);
                    
                    if (request.ValidateSchema)
                    {
                        var errors = ValidateSchema(schema, page.Id.ToString());
                        validationErrors.AddRange(errors);
                    }

                    if (request.MinifyOutput)
                    {
                        schema = MinifyJsonSchema(schema);
                    }

                    pageSchemas[page.Id.ToString()] = schema;

                    // Count schema types
                    var schemaType = ExtractSchemaType(schema);
                    if (!string.IsNullOrEmpty(schemaType))
                    {
                        schemaTypeCounts[schemaType] = schemaTypeCounts.GetValueOrDefault(schemaType, 0) + 1;
                    }
                }
                catch (Exception ex)
                {
                    validationErrors.Add(new SchemaValidationError
                    {
                        PageId = page.Id.ToString(),
                        ErrorMessage = ex.Message,
                        Severity = "Error"
                    });
                }
            }

            var statistics = new SchemaStatistics
            {
                TotalSchemas = pageSchemas.Count,
                ValidSchemas = pageSchemas.Count - validationErrors.Count(e => e.Severity == "Error"),
                InvalidSchemas = validationErrors.Count(e => e.Severity == "Error"),
                SchemaTypes = schemaTypeCounts,
                TotalProperties = CalculateTotalSchemaProperties(pageSchemas.Values)
            };

            return new SchemaMarkupResult
            {
                PageSchemas = pageSchemas,
                ValidationErrors = validationErrors,
                Statistics = statistics
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating schema markup");
            throw new InvalidOperationException($"Schema generation failed: {ex.Message}", ex);
        }
    }

    public async Task<GenerationPerformanceAnalysis> AnalyzeGenerationPerformanceAsync(string templateId, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Analyzing generation performance for template {TemplateId}", templateId);

            var template = await _context.Set<SeoTemplate>()
                .FirstOrDefaultAsync(t => t.Id.ToString() == templateId, cancellationToken);

            if (template == null)
            {
                throw new InvalidOperationException($"Template not found: {templateId}");
            }

            // Get recent pages generated with this template
            var recentPages = await _context.Set<SeoPage>()
                .Where(p => p.TemplateId.ToString() == templateId && p.CreatedAt >= DateTime.UtcNow.AddDays(-30))
                .OrderByDescending(p => p.CreatedAt)
                .ToListAsync(cancellationToken);

            // Calculate overall performance metrics  
            var overallPerformance = new PerformanceMetrics
            {
                AverageViews = recentPages.Any() ? recentPages.Average(p => p.SeoScore) : 0,
                AverageClicks = CalculateThroughput(recentPages),
                AverageImpressions = recentPages.Count,
                AverageClickThroughRate = CalculateSuccessRate(recentPages) / 100.0,
                AveragePosition = CalculateErrorRate(recentPages),
                AverageBounceRate = 0.0,
                AverageTimeOnPage = CalculateAverageGenerationTime(recentPages)
            };

            // Calculate trends
            var trends = CalculatePerformanceTrends(recentPages);

            // Identify bottlenecks
            var bottlenecks = IdentifyPerformanceBottlenecks(template, recentPages);

            // Generate recommendations
            var recommendations = GeneratePerformanceRecommendations(overallPerformance, bottlenecks);

            // Calculate resource metrics
            var resourceMetrics = new ResourceUtilizationMetrics
            {
                MemoryUtilization = GetAverageMemoryUtilization(recentPages),
                CpuUtilization = GetAverageCpuUtilization(recentPages),
                DiskUtilization = GetAverageDiskUtilization(recentPages),
                NetworkUtilization = GetAverageNetworkUtilization(recentPages),
                ActiveConnections = GetAverageActiveConnections()
            };

            return new GenerationPerformanceAnalysis
            {
                TemplateId = int.TryParse(templateId, out var tId) ? tId : 0,
                OverallPerformance = overallPerformance,
                Trends = trends,
                Bottlenecks = bottlenecks,
                Recommendations = recommendations.Select(r => new PerformanceRecommendation { Category = r.Category, Title = r.Title, Description = r.Description, Priority = r.Priority == "high" ? 3.0 : r.Priority == "medium" ? 2.0 : 1.0, EstimatedImprovement = 0.5 }),
                ResourceMetrics = resourceMetrics
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error analyzing generation performance for template {TemplateId}", templateId);
            throw new InvalidOperationException($"Performance analysis failed: {ex.Message}", ex);
        }
    }

    #region Private Helper Methods

    private async Task ProcessSinglePageGeneration(
        BatchGenerationRequest request, 
        Dictionary<string, object> dataSet, 
        int index,
        List<SeoPage> generatedPages, 
        List<GenerationError> errors, 
        SemaphoreSlim semaphore, 
        CancellationToken cancellationToken)
    {
        await semaphore.WaitAsync(cancellationToken);
        try
        {
            var pageRequest = new PageGenerationRequest
            {
                TemplateId = request.TemplateId,
                Variables = dataSet,
                Status = request.PublishImmediately ? SeoPageStatus.Published : SeoPageStatus.Draft,
                OptimizeForSeo = request.OptimizeForSeo,
                GenerateSchemaMarkup = request.GenerateSchemaMarkup,
                ValidateQuality = request.ValidateQuality,
                Category = request.Category,
                Author = request.Author,
                Options = request.Options
            };

            var page = await GeneratePageAsync(pageRequest, cancellationToken);
            lock (generatedPages)
            {
                generatedPages.Add(page);
            }
        }
        catch (Exception ex)
        {
            lock (errors)
            {
                errors.Add(new GenerationError
                {
                    PageId = $"batch-{index}",
                    ErrorCode = "GENERATION_FAILED",
                    Message = ex.Message,
                    StackTrace = ex.StackTrace,
                    Context = new Dictionary<string, object> { ["dataSet"] = dataSet, ["index"] = index }
                });
            }
        }
        finally
        {
            semaphore.Release();
        }
    }

    private BatchGenerationMetrics CalculateBatchMetrics(List<SeoPage> pages, TimeSpan duration)
    {
        var throughput = pages.Count / Math.Max(duration.TotalSeconds, 1);
        var avgGenerationTime = duration.TotalSeconds / Math.Max(pages.Count, 1);
        var avgQualityScore = pages.Any() ? pages.Average(p => p.SeoScore) : 0;

        return new BatchGenerationMetrics
        {
            ThroughputPagesPerSecond = throughput,
            AveragePageGenerationTime = avgGenerationTime,
            AverageQualityScore = avgQualityScore,
            PeakMemoryUsage = GetPeakMemoryUsage(),
            CpuUtilization = GetAverageCpuUsage()
        };
    }

    private string GenerateSlug(string title)
    {
        return Regex.Replace(title.ToLower(), @"[^a-z0-9]+", "-").Trim('-');
    }

    private string GenerateUrl(string slug)
    {
        return $"/content/{slug}";
    }

    private int CountWords(string content)
    {
        var cleanContent = Regex.Replace(content, @"<[^>]+>", "");
        return cleanContent.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length;
    }

    private async Task<SeoPage> OptimizePageForSeo(SeoPage page, List<string> keywords)
    {
        // Implement SEO optimization logic
        if (keywords.Any())
        {
            // Ensure primary keyword is in title
            var primaryKeyword = keywords.First();
            if (!page.Title.Contains(primaryKeyword, StringComparison.OrdinalIgnoreCase))
            {
                page.Title = $"{primaryKeyword} - {page.Title}";
            }

            // Optimize meta description
            if (!page.MetaDescription.Contains(primaryKeyword, StringComparison.OrdinalIgnoreCase))
            {
                page.MetaDescription = $"{primaryKeyword}: {page.MetaDescription}";
            }
        }

        return page;
    }

    private TimeSpan? CalculateEstimatedTimeRemaining(SeoGenerationJob job)
    {
        if (job.Status != SeoJobStatus.Running || job.ProcessedCount == 0)
            return null;

        var elapsed = DateTime.UtcNow - (job.StartedAt ?? DateTime.UtcNow);
        var avgTimePerItem = elapsed.TotalSeconds / job.ProcessedCount;
        var remainingItems = job.BatchSize - job.ProcessedCount;

        return TimeSpan.FromSeconds(avgTimePerItem * remainingItems);
    }

    private double CalculateCurrentThroughput(SeoGenerationJob job)
    {
        if (job.Status != SeoJobStatus.Running || job.StartedAt == null)
            return 0;

        var elapsed = DateTime.UtcNow - job.StartedAt.Value;
        return job.ProcessedCount / Math.Max(elapsed.TotalSeconds, 1);
    }

    private double CalculateAverageGenerationTime(SeoGenerationJob job)
    {
        if (job.ProcessedCount == 0 || job.StartedAt == null)
            return 0;

        var elapsed = DateTime.UtcNow - job.StartedAt.Value;
        return elapsed.TotalSeconds / job.ProcessedCount;
    }

    private int GetCurrentMemoryUsage()
    {
        return (int)(GC.GetTotalMemory(false) / 1024 / 1024); // MB
    }

    private double GetCurrentCpuUsage()
    {
        // Simplified CPU usage - in production, would use performance counters
        return Environment.ProcessorCount * 50.0; // Placeholder
    }

    private int GetPeakMemoryUsage()
    {
        return GetCurrentMemoryUsage(); // Simplified
    }

    private double GetAverageCpuUsage()
    {
        return GetCurrentCpuUsage(); // Simplified
    }

    private GenerationComplexityScore CalculateGenerationComplexity(PageGenerationRequest request)
    {
        var variableCount = request.Variables.Count;
        var templateComplexity = Math.Min(variableCount / 10.0 * 100, 100);
        var dataComplexity = Math.Min(request.Variables.Values.Count(v => v is IEnumerable<object>) / 5.0 * 100, 100);
        var processingComplexity = (request.OptimizeForSeo ? 25 : 0) + (request.GenerateSchemaMarkup ? 25 : 0) + (request.ValidateQuality ? 25 : 0);

        var overall = (templateComplexity + dataComplexity + processingComplexity) / 3.0;

        return new GenerationComplexityScore
        {
            Overall = overall,
            TemplateComplexity = templateComplexity,
            DataComplexity = dataComplexity,
            ProcessingComplexity = processingComplexity,
            Level = overall switch
            {
                < 25 => GenerationComplexityLevel.Simple,
                < 50 => GenerationComplexityLevel.Moderate,
                < 75 => GenerationComplexityLevel.Complex,
                _ => GenerationComplexityLevel.Expert
            }
        };
    }

    private EstimatedResources EstimateResources(PageGenerationRequest request)
    {
        var complexity = CalculateGenerationComplexity(request);
        var baseTime = TimeSpan.FromSeconds(2);
        var multiplier = complexity.Overall / 50.0;

        return new EstimatedResources
        {
            EstimatedTime = TimeSpan.FromSeconds(baseTime.TotalSeconds * multiplier),
            EstimatedMemoryUsage = (int)(50 * multiplier), // MB
            EstimatedCpuUsage = (int)(25 * multiplier), // Percentage
            EstimatedDiskSpace = (int)(10 * multiplier), // MB
            EstimatedCost = 0.01 * multiplier // USD
        };
    }

    private async Task<SeoAnalysisResult> AnalyzeSeoForPreview(GeoLeap.Api.ProgrammaticSeo.Models.ProcessedTemplate template, List<string> keywords)
    {
        var titleScore = AnalyzeTitleSeo(template.Title, keywords);
        var metaScore = AnalyzeMetaDescriptionSeo(template.MetaDescription, keywords);
        var contentScore = AnalyzeContentSeo(template.Content, keywords);
        var keywordScore = AnalyzeKeywordUsage(template.Content, keywords);
        var structureScore = AnalyzeContentStructure(template.Content);

        var overallScore = (titleScore + metaScore + contentScore + keywordScore + structureScore) / 5.0;

        var issues = new List<SeoIssue>();
        if (titleScore < 70) issues.Add(new SeoIssue { Type = "Title", Message = "Title could be optimized", Severity = "Warning" });
        if (metaScore < 70) issues.Add(new SeoIssue { Type = "Meta", Message = "Meta description needs improvement", Severity = "Warning" });
        if (contentScore < 70) issues.Add(new SeoIssue { Type = "Content", Message = "Content structure could be improved", Severity = "Info" });

        return new SeoAnalysisResult
        {
            OverallScore = overallScore,
            TitleScore = titleScore,
            MetaDescriptionScore = metaScore,
            ContentScore = contentScore,
            KeywordScore = keywordScore,
            StructureScore = structureScore,
            Issues = issues
        };
    }

    private IEnumerable<PreviewRecommendation> GeneratePreviewRecommendations(GeoLeap.Api.ProgrammaticSeo.Models.ProcessedTemplate template, SeoAnalysisResult seoAnalysis)
    {
        var recommendations = new List<PreviewRecommendation>();

        if (seoAnalysis.OverallScore < 80)
        {
            recommendations.Add(new PreviewRecommendation
            {
                Type = "SEO",
                Title = "Improve Overall SEO Score",
                Description = "Consider optimizing title, meta description, and content structure",
                Priority = 80,
                ActionRequired = "Review SEO issues and apply fixes"
            });
        }

        if (template.QualityScore < 0.70)
        {
            recommendations.Add(new PreviewRecommendation
            {
                Type = "Quality",
                Title = "Improve Content Quality",
                Description = "Content quality score is below optimal. Consider improving readability and structure.",
                Priority = 70,
                ActionRequired = "Review content quality recommendations"
            });
        }

        return recommendations.OrderByDescending(r => r.Priority);
    }

    // Additional helper methods for SEO analysis, data processing, etc.
    private double AnalyzeTitleSeo(string title, List<string> keywords)
    {
        var score = 50.0;
        if (title.Length >= 30 && title.Length <= 60) score += 25;
        if (keywords.Any(k => title.Contains(k, StringComparison.OrdinalIgnoreCase))) score += 25;
        return Math.Min(100, score);
    }

    private double AnalyzeMetaDescriptionSeo(string metaDescription, List<string> keywords)
    {
        var score = 50.0;
        if (metaDescription.Length >= 120 && metaDescription.Length <= 160) score += 25;
        if (keywords.Any(k => metaDescription.Contains(k, StringComparison.OrdinalIgnoreCase))) score += 25;
        return Math.Min(100, score);
    }

    private double AnalyzeContentSeo(string content, List<string> keywords)
    {
        var score = 50.0;
        var wordCount = CountWords(content);
        if (wordCount >= 300) score += 25;
        if (keywords.Any(k => content.Contains(k, StringComparison.OrdinalIgnoreCase))) score += 25;
        return Math.Min(100, score);
    }

    private double AnalyzeKeywordUsage(string content, List<string> keywords)
    {
        if (!keywords.Any()) return 50;

        var wordCount = CountWords(content);
        var totalKeywordOccurrences = keywords.Sum(k => Regex.Matches(content, Regex.Escape(k), RegexOptions.IgnoreCase).Count);
        var density = (totalKeywordOccurrences / (double)wordCount) * 100;

        if (density >= 1 && density <= 3) return 100;
        if (density < 0.5 || density > 5) return 30;
        return 70;
    }

    private double AnalyzeContentStructure(string content)
    {
        var score = 50.0;
        if (Regex.IsMatch(content, @"<h[1-6]", RegexOptions.IgnoreCase)) score += 25;
        if (Regex.IsMatch(content, @"<p>", RegexOptions.IgnoreCase)) score += 25;
        return Math.Min(100, score);
    }

    // Data source and processing methods
    private async Task<IEnumerable<Dictionary<string, object>>> RetrieveDataFromSource(DataSourceConfig config, GenerationFilters? filters, CancellationToken cancellationToken)
    {
        // Implementation would depend on data source type
        return new List<Dictionary<string, object>>();
    }

    private async Task<IEnumerable<Dictionary<string, object>>> MapData(IEnumerable<Dictionary<string, object>> data, DataMappingConfig mapping, CancellationToken cancellationToken)
    {
        // Implementation for data mapping
        return data;
    }

    private IEnumerable<Dictionary<string, object>> ApplyDataFilters(IEnumerable<Dictionary<string, object>> data, GenerationFilters filters)
    {
        // Implementation for data filtering
        return data;
    }

    private int CountDuplicates(IEnumerable<Dictionary<string, object>> data)
    {
        // Implementation for duplicate counting
        return 0;
    }

    private IEnumerable<DataProcessingError> ConvertToDataProcessingErrors(IEnumerable<GenerationError> errors)
    {
        return errors.Select(e => new DataProcessingError
        {
            ErrorType = e.ErrorCode,
            Message = e.Message
        });
    }

    private IEnumerable<GenerationTrend> CalculateGenerationTrends(List<SeoPage> pages)
    {
        return pages.GroupBy(p => p.CreatedAt.Date)
            .Select(g => new GenerationTrend
            {
                Date = g.Key,
                PagesGenerated = g.Count(),
                AverageQualityScore = g.Average(p => p.SeoScore),
                AverageGenerationTime = 2.0 // Placeholder
            });
    }

    private IEnumerable<TemplateUsageMetric> CalculateTemplateUsageMetrics(List<SeoPage> pages)
    {
        return pages.GroupBy(p => p.TemplateId)
            .Select(g => new TemplateUsageMetric
            {
                TemplateId = g.Key,
                TemplateName = g.First().Template?.Name ?? "Unknown",
                UsageCount = g.Count(),
                AveragePerformance = g.Average(p => p.SeoScore)
            });
    }

    private async Task<GenerationResourceUsage> CalculateResourceUsage(TimeSpan period)
    {
        // Implementation for resource usage calculation
        return new GenerationResourceUsage
        {
            AverageMemoryUsage = 50.0,
            AverageCpuUsage = 25.0,
            AverageDiskIo = 10.0,
            AverageNetworkIo = 5.0
        };
    }

    private double CalculateAverageGenerationTime(List<SeoPage> pages)
    {
        // Simplified calculation - in production would track actual generation times
        return 2.0; // seconds
    }

    private double CalculateSuccessRate(List<SeoPage> pages)
    {
        if (!pages.Any()) return 0;
        var successfulPages = pages.Count(p => p.Status != SeoPageStatus.Error);
        return (successfulPages / (double)pages.Count) * 100;
    }

    // Additional helper methods for new functionality
    private int DetermineOptimalConcurrency(OptimizationCriteria criteria)
    {
        return criteria.OptimizationFocus switch
        {
            "speed" => Math.Min(Environment.ProcessorCount * 2, 16),
            "quality" => Math.Max(1, Environment.ProcessorCount / 2),
            _ => Environment.ProcessorCount
        };
    }

    private TimeSpan DetermineOptimalTimeout(OptimizationCriteria criteria)
    {
        return criteria.OptimizationFocus switch
        {
            "speed" => TimeSpan.FromMinutes(1),
            "quality" => TimeSpan.FromMinutes(10),
            _ => criteria.MaxGenerationTime
        };
    }

    private int DetermineOptimalBatchSize(OptimizationCriteria criteria)
    {
        return criteria.OptimizationFocus switch
        {
            "speed" => 100,
            "quality" => 25,
            _ => 50
        };
    }

    private IEnumerable<OptimizationRecommendation> GenerateOptimizationRecommendations(SeoTemplate template, List<SeoPage> recentPages, OptimizationCriteria criteria)
    {
        var recommendations = new List<OptimizationRecommendation>();

        if (recentPages.Any() && recentPages.Average(p => p.SeoScore) < criteria.TargetQualityScore)
        {
            recommendations.Add(new OptimizationRecommendation
            {
                Type = "Quality",
                Title = "Improve Template Content Quality",
                Description = "Consider refining template content structure and SEO elements",
                Impact = 0.8
            });
        }

        if (criteria.OptimizationFocus == "speed")
        {
            recommendations.Add(new OptimizationRecommendation
            {
                Type = "Performance",
                Title = "Increase Concurrency Level",
                Description = "Use higher concurrency for faster batch processing",
                Impact = 0.6
            });
        }

        return recommendations;
    }

    private IQueryable<SeoPage> ApplyExportFilters(IQueryable<SeoPage> query, PageExportFilter filter)
    {
        if (!string.IsNullOrEmpty(filter.Category))
            query = query.Where(p => p.Category == filter.Category);

        if (filter.Status.HasValue)
            query = query.Where(p => p.Status == filter.Status.Value);

        if (filter.CreatedAfter.HasValue)
            query = query.Where(p => p.CreatedAt >= filter.CreatedAfter.Value);

        if (filter.CreatedBefore.HasValue)
            query = query.Where(p => p.CreatedAt <= filter.CreatedBefore.Value);

        if (filter.MinPerformanceScore.HasValue)
            query = query.Where(p => p.SeoScore >= filter.MinPerformanceScore.Value);

        if (!string.IsNullOrEmpty(filter.TemplateId))
            query = query.Where(p => p.TemplateId.ToString() == filter.TemplateId);

        return query;
    }

    private string ConvertToCsv(object data)
    {
        // Simplified CSV conversion - in production would use a proper CSV library
        return "Id,Title,Slug,Status,CreatedAt\n" + 
               "sample-id,Sample Title,sample-slug,Published,2023-01-01";
    }

    private string ConvertToXml(object data)
    {
        // Simplified XML conversion
        return "<?xml version=\"1.0\"?><pages><page><id>sample</id><title>Sample</title></page></pages>";
    }

    private byte[] ApplyCompression(byte[] data, CompressionFormat compression)
    {
        // Simplified compression - in production would implement actual compression
        return data;
    }

    private string GetCompressionExtension(CompressionFormat compression)
    {
        return compression switch
        {
            CompressionFormat.Zip => ".zip",
            CompressionFormat.Gzip => ".gz",
            _ => string.Empty
        };
    }

    private IEnumerable<ImportItem> ParseImportData(byte[] data, ImportFormat format)
    {
        // Simplified parsing - in production would implement proper format parsing
        return new List<ImportItem>
        {
            new ImportItem
            {
                Title = "Sample Imported Page",
                Slug = "sample-imported",
                Content = "Sample content",
                Status = "Draft"
            }
        };
    }

    private IEnumerable<string> ValidateImportItem(ImportItem item)
    {
        var errors = new List<string>();
        
        if (string.IsNullOrEmpty(item.Title))
            errors.Add("Title is required");
            
        if (string.IsNullOrEmpty(item.Slug))
            errors.Add("Slug is required");
            
        return errors;
    }

    private IQueryable<SeoPage> ApplySitemapFilters(IQueryable<SeoPage> query, SitemapFilter filter)
    {
        if (filter.Status.HasValue)
            query = query.Where(p => p.Status == filter.Status.Value);

        if (filter.ModifiedAfter.HasValue)
            query = query.Where(p => p.UpdatedAt >= filter.ModifiedAfter.Value);

        if (!string.IsNullOrEmpty(filter.Category))
            query = query.Where(p => p.Category == filter.Category);

        if (filter.IndexableOnly == true)
            query = query.Where(p => p.Status == SeoPageStatus.Published);

        return query;
    }

    private string GenerateXmlSitemap(List<SeoPage> pages, SitemapGenerationRequest request)
    {
        var baseUrl = request.BaseUrl ?? "https://example.com";
        var sitemap = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        sitemap += "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";

        foreach (var page in pages)
        {
            sitemap += "<url>\n";
            sitemap += $"  <loc>{baseUrl}{page.Url}</loc>\n";
            sitemap += $"  <lastmod>{page.UpdatedAt:yyyy-MM-dd}</lastmod>\n";
            sitemap += $"  <priority>0.8</priority>\n";
            sitemap += "</url>\n";
        }

        sitemap += "</urlset>";
        return sitemap;
    }

    private string GenerateTextSitemap(List<SeoPage> pages, SitemapGenerationRequest request)
    {
        var baseUrl = request.BaseUrl ?? "https://example.com";
        return string.Join("\n", pages.Select(p => $"{baseUrl}{p.Url}"));
    }

    private int CountImageUrls(List<SeoPage> pages)
    {
        return pages.Sum(p => Regex.Matches(p.Content, @"<img[^>]+>", RegexOptions.IgnoreCase).Count);
    }

    private int CountVideoUrls(List<SeoPage> pages)
    {
        return pages.Sum(p => Regex.Matches(p.Content, @"<video[^>]+>", RegexOptions.IgnoreCase).Count);
    }

    private async Task<string> GenerateSchemaForPage(SeoPage page, string? schemaType, SchemaFormat format)
    {
        var schema = new
        {
            context = "https://schema.org",
            type = schemaType ?? "Article",
            headline = page.Title,
            description = page.MetaDescription,
            url = page.Url,
            datePublished = page.PublishedAt?.ToString("yyyy-MM-dd"),
            dateModified = page.UpdatedAt?.ToString("yyyy-MM-dd"),
            wordCount = page.WordCount
        };

        return JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true });
    }

    private IEnumerable<SchemaValidationError> ValidateSchema(string schema, string pageId)
    {
        var errors = new List<SchemaValidationError>();
        
        try
        {
            JsonSerializer.Deserialize<object>(schema);
        }
        catch (JsonException ex)
        {
            errors.Add(new SchemaValidationError
            {
                PageId = pageId,
                ErrorMessage = "Invalid JSON format: " + ex.Message,
                Severity = "Error"
            });
        }

        return errors;
    }

    private string MinifyJsonSchema(string schema)
    {
        try
        {
            var parsed = JsonSerializer.Deserialize<object>(schema);
            return JsonSerializer.Serialize(parsed);
        }
        catch
        {
            return schema;
        }
    }

    private string ExtractSchemaType(string schema)
    {
        try
        {
            using var doc = JsonDocument.Parse(schema);
            if (doc.RootElement.TryGetProperty("@type", out var typeElement) ||
                doc.RootElement.TryGetProperty("type", out typeElement))
            {
                return typeElement.GetString() ?? "Unknown";
            }
        }
        catch
        {
            // Ignore parsing errors
        }
        return "Unknown";
    }

    private int CalculateTotalSchemaProperties(IEnumerable<string> schemas)
    {
        return schemas.Sum(schema =>
        {
            try
            {
                using var doc = JsonDocument.Parse(schema);
                return CountJsonProperties(doc.RootElement);
            }
            catch
            {
                return 0;
            }
        });
    }

    private int CountJsonProperties(JsonElement element)
    {
        return element.ValueKind switch
        {
            JsonValueKind.Object => element.EnumerateObject().Sum(prop => 1 + CountJsonProperties(prop.Value)),
            JsonValueKind.Array => element.EnumerateArray().Sum(CountJsonProperties),
            _ => 0
        };
    }

    private double CalculateThroughput(List<SeoPage> pages)
    {
        if (!pages.Any()) return 0;
        var timeSpan = pages.Max(p => p.CreatedAt) - pages.Min(p => p.CreatedAt);
        return timeSpan.TotalHours > 0 ? pages.Count / timeSpan.TotalHours : 0;
    }

    private double CalculateErrorRate(List<SeoPage> pages)
    {
        if (!pages.Any()) return 0;
        var errorPages = pages.Count(p => p.Status == SeoPageStatus.Error);
        return (errorPages / (double)pages.Count) * 100;
    }

    private IEnumerable<PerformanceTrend> CalculatePerformanceTrends(List<SeoPage> pages)
    {
        return pages.GroupBy(p => p.CreatedAt.Date)
            .Select(g => new PerformanceTrend
            {
                Metric = "GenerationTrend",
                Data = new List<AdvancedDataPoint>
                {
                    new AdvancedDataPoint
                    {
                        Date = g.Key,
                        Value = g.Average(p => p.SeoScore),
                        Metadata = new Dictionary<string, object>
                        {
                            ["count"] = g.Count(),
                            ["errorRate"] = 0.0 // g.Count(p => p.Status == SeoPageStatus.Error) / (double)g.Count() * 100
                        }
                    }
                },
                TrendDirection = 0.0,
                TrendStrength = 0.0
            });
    }

    private IEnumerable<PerformanceBottleneck> IdentifyPerformanceBottlenecks(SeoTemplate template, List<SeoPage> pages)
    {
        var bottlenecks = new List<PerformanceBottleneck>();

        if (pages.Any() && pages.Average(p => p.SeoScore) < 70)
        {
            bottlenecks.Add(new PerformanceBottleneck
            {
                Component = "Content Quality",
                Description = "Average SEO score is below optimal threshold",
                Impact = 0.7,
                Resolution = "Review and optimize template content structure"
            });
        }

        if (template.VariablesList.Count > 20)
        {
            bottlenecks.Add(new PerformanceBottleneck
            {
                Component = "Template Complexity",
                Description = "High number of template variables may slow generation",
                Impact = 0.5,
                Resolution = "Consider simplifying template or optimizing variable processing"
            });
        }

        return bottlenecks;
    }

    private IEnumerable<GeoLeap.Api.Models.PerformanceRecommendation> GeneratePerformanceRecommendations(PerformanceMetrics performance, IEnumerable<PerformanceBottleneck> bottlenecks)
    {
        var recommendations = new List<GeoLeap.Api.Models.PerformanceRecommendation>();

        if (performance.AverageViews < 80)
        {
            recommendations.Add(new GeoLeap.Api.Models.PerformanceRecommendation
            {
                Category = "Quality",
                Title = "Improve Content Quality", 
                Description = "Focus on improving SEO optimization and content structure",
                EstimatedImpact = "0.8",
                Priority = "High",
                Impact = "High",
                EstimatedEffort = "Medium"
            });
        }

        if (performance.AverageClicks < 100)
        {
            recommendations.Add(new GeoLeap.Api.Models.PerformanceRecommendation
            {
                Category = "Performance",
                Title = "Increase Processing Speed",
                Description = "Consider increasing concurrency or optimizing generation pipeline",
                EstimatedImpact = "0.6",
                Priority = "Medium",
                Impact = "Medium",
                EstimatedEffort = "Low"
            });
        }

        return recommendations;
    }

    private double GetAverageMemoryUtilization(List<SeoPage> pages)
    {
        // Simplified calculation
        return 45.0 + (pages.Count * 0.1);
    }

    private double GetAverageCpuUtilization(List<SeoPage> pages)
    {
        // Simplified calculation
        return 25.0 + (pages.Count * 0.05);
    }

    private double GetAverageDiskUtilization(List<SeoPage> pages)
    {
        // Simplified calculation
        return 15.0 + (pages.Count * 0.02);
    }

    private double GetAverageNetworkUtilization(List<SeoPage> pages)
    {
        // Simplified calculation
        return 5.0 + (pages.Count * 0.01);
    }

    private int GetAverageActiveConnections()
    {
        // Simplified calculation
        return 10;
    }

    public async Task<SeoPage> RegeneratePageAsync(long pageId, Dictionary<string, object>? newData = null, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Regenerating page with ID {PageId}", pageId);

            var existingPage = await _context.Set<SeoPage>()
                .Include(p => p.Template)
                .FirstOrDefaultAsync(p => p.Id == pageId, cancellationToken);

            if (existingPage == null)
                throw new ArgumentException($"Page with ID {pageId} not found");

            // Create new request with existing or updated data
            var request = new PageGenerationRequest
            {
                TemplateId = existingPage.TemplateId,
                Variables = newData ?? JsonSerializer.Deserialize<Dictionary<string, object>>(existingPage.VariableValues) ?? new(),
                Slug = existingPage.Slug,
                Title = existingPage.Title,
                MetaDescription = existingPage.MetaDescription,
                Status = existingPage.Status,
                OptimizeForSeo = true,
                GenerateSchemaMarkup = true,
                ValidateQuality = true
            };

            // Generate new page content
            var regeneratedPage = await GeneratePageAsync(request, cancellationToken);

            // Update existing page with new content
            existingPage.Content = regeneratedPage.Content;
            existingPage.MetaTitle = regeneratedPage.MetaTitle;
            existingPage.MetaDescription = regeneratedPage.MetaDescription;
            existingPage.H1 = regeneratedPage.H1;
            existingPage.WordCount = regeneratedPage.WordCount;
            existingPage.ReadingTimeMinutes = regeneratedPage.ReadingTimeMinutes;
            existingPage.SeoScore = regeneratedPage.SeoScore;
            existingPage.LastUpdated = DateTime.UtcNow;
            existingPage.VariableValues = regeneratedPage.VariableValues;

            await _context.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("Successfully regenerated page {PageId}", pageId);
            return existingPage;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error regenerating page {PageId}", pageId);
            throw new InvalidOperationException($"Page regeneration failed: {ex.Message}", ex);
        }
    }

    public async Task<BulkRegenerationResult> RegeneratePagesAsync(IEnumerable<long> pageIds, RegenerationOptions? options = null, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Starting bulk regeneration for {Count} pages", pageIds.Count());

            var result = new BulkRegenerationResult();
            var updatedPages = new List<SeoPage>();
            var errors = new List<RegenerationError>();

            result.TotalPages = pageIds.Count();

            foreach (var pageId in pageIds)
            {
                try
                {
                    var regeneratedPage = await RegeneratePageAsync(pageId, options?.NewData, cancellationToken);
                    updatedPages.Add(regeneratedPage);
                    result.RegeneratedPages++;
                }
                catch (ArgumentException)
                {
                    result.SkippedPages++;
                    errors.Add(new RegenerationError
                    {
                        PageId = pageId.ToString(),
                        ErrorCode = "PAGE_NOT_FOUND",
                        Message = $"Page with ID {pageId} not found"
                    });
                }
                catch (Exception ex)
                {
                    result.FailedPages++;
                    errors.Add(new RegenerationError
                    {
                        PageId = pageId.ToString(),
                        ErrorCode = "REGENERATION_FAILED",
                        Message = ex.Message
                    });
                }
            }

            result.UpdatedPages = updatedPages;
            result.Errors = errors;
            result.Duration = TimeSpan.FromSeconds(result.TotalPages * 2); // Estimated

            _logger.LogInformation("Completed bulk regeneration: {Regenerated} succeeded, {Failed} failed, {Skipped} skipped", 
                result.RegeneratedPages, result.FailedPages, result.SkippedPages);

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in bulk regeneration");
            throw new InvalidOperationException($"Bulk regeneration failed: {ex.Message}", ex);
        }
    }

    public async Task<BulkOperationResult> ArchivePagesAsync(IEnumerable<long> pageIds, bool permanent = false, CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Archiving {Count} pages (permanent: {Permanent})", pageIds.Count(), permanent);

            var result = new BulkOperationResult();
            var affectedPages = new List<SeoPage>();
            var errors = new List<OperationError>();

            result.TotalPages = pageIds.Count();

            var pages = await _context.Set<SeoPage>()
                .Where(p => pageIds.Contains(p.Id))
                .ToListAsync(cancellationToken);

            foreach (var pageId in pageIds)
            {
                var page = pages.FirstOrDefault(p => p.Id == pageId);
                if (page == null)
                {
                    // result.SkippedItems not available in ISeoPageGenerationService BulkOperationResult
                    errors.Add(new OperationError
                    {
                        ItemId = pageId.ToString(),
                        ErrorCode = "PAGE_NOT_FOUND",
                        Message = $"Page with ID {pageId} not found"
                    });
                    continue;
                }

                try
                {
                    if (permanent)
                    {
                        _context.Set<SeoPage>().Remove(page);
                    }
                    else
                    {
                        page.Status = SeoPageStatus.Archived;
                        page.LastUpdated = DateTime.UtcNow;
                    }

                    affectedPages.Add(page);
                    result.SuccessfulOperations++;
                }
                catch (Exception ex)
                {
                    result.FailedOperations++;
                    errors.Add(new OperationError
                    {
                        ItemId = pageId.ToString(),
                        ErrorCode = "ARCHIVE_FAILED",
                        Message = ex.Message
                    });
                }
            }

            await _context.SaveChangesAsync(cancellationToken);

            // result.AffectedItems not available in ISeoPageGenerationService BulkOperationResult
            result.Errors = errors.Select(e => new BulkOperationError { PageId = e.ItemId, ErrorMessage = e.Message, Operation = "Archive" });
            result.Duration = TimeSpan.FromSeconds(result.TotalPages * 0.5); // Estimated

            _logger.LogInformation("Completed archiving: {Successful} succeeded, {Failed} failed, {Skipped} skipped", 
                result.SuccessfulOperations, result.FailedOperations, affectedPages.Count);

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error archiving pages");
            throw new InvalidOperationException($"Archive operation failed: {ex.Message}", ex);
        }
    }

    #endregion
}

// Supporting classes for new functionality
internal class ImportItem
{
    public string? Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Slug { get; set; } = string.Empty;
    public string? Url { get; set; }
    public string Content { get; set; } = string.Empty;
    public string MetaDescription { get; set; } = string.Empty;
    public string MetaKeywords { get; set; } = string.Empty;
    public string? TemplateId { get; set; }
    public string Status { get; set; } = "Draft";
    public DateTime? CreatedAt { get; set; }
}