using System.Net;
using System.Text.Json;
using Xunit;
using GeoLeap.Api.Tests.Infrastructure;
using System.Net.Http.Headers;

namespace GeoLeap.Api.Tests;

/// <summary>
/// CRITICAL AUTH FLOW DEBUG TEST
/// Purpose: Isolate and debug authentication flow issues causing 500 errors instead of 401
/// </summary>
[Collection("NonParallel")]
public class AUTH_FLOW_DEBUG_TEST : StableTestBase
{
    [Fact]
    public async Task Debug_Auth_Endpoint_Without_Token()
    {
        // Test 1: No authentication header at all
        Console.WriteLine("🔍 TEST 1: Testing /api/auth/me WITHOUT any authentication header");
        var response1 = await Client.GetAsync("/api/auth/me");
        var content1 = await response1.Content.ReadAsStringAsync();
        
        Console.WriteLine($"   Status: {response1.StatusCode} ({(int)response1.StatusCode})");
        Console.WriteLine($"   Content: {content1.Substring(0, Math.Min(300, content1.Length))}");
        Console.WriteLine($"   Headers: {string.Join(", ", response1.Headers.Select(h => $"{h.Key}:{string.Join(",", h.Value)}"))}");
        
        // The goal: Should be 401 Unauthorized, not 500 Internal Server Error
        Console.WriteLine($"   EXPECTED: 401 Unauthorized");
        Console.WriteLine($"   ACTUAL: {response1.StatusCode}");
        Console.WriteLine($"   SUCCESS: {(response1.StatusCode == HttpStatusCode.Unauthorized ? "✅ PASS" : "❌ FAIL")}");
    }
    
    [Fact]
    public async Task Debug_Auth_Endpoint_With_Invalid_Token()
    {
        // Test 2: Invalid Bearer token
        Console.WriteLine("🔍 TEST 2: Testing /api/auth/me WITH invalid Bearer token");
        Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "invalid-token-12345");
        
        var response2 = await Client.GetAsync("/api/auth/me");
        var content2 = await response2.Content.ReadAsStringAsync();
        
        Console.WriteLine($"   Status: {response2.StatusCode} ({(int)response2.StatusCode})");
        Console.WriteLine($"   Content: {content2.Substring(0, Math.Min(300, content2.Length))}");
        
        // Clear auth header for other tests
        Client.DefaultRequestHeaders.Authorization = null;
        
        Console.WriteLine($"   EXPECTED: 401 Unauthorized");
        Console.WriteLine($"   ACTUAL: {response2.StatusCode}");
        Console.WriteLine($"   SUCCESS: {(response2.StatusCode == HttpStatusCode.Unauthorized ? "✅ PASS" : "❌ FAIL")}");
    }
    
    [Fact]
    public async Task Debug_Auth_Endpoint_With_Valid_Token()
    {
        // Test 3: Valid JWT token (generated by StableTestBase)
        Console.WriteLine("🔍 TEST 3: Testing /api/auth/me WITH valid JWT token");
        SetAuthenticationHeader("test-user-123");
        
        var response3 = await Client.GetAsync("/api/auth/me");
        var content3 = await response3.Content.ReadAsStringAsync();
        
        Console.WriteLine($"   Status: {response3.StatusCode} ({(int)response3.StatusCode})");
        Console.WriteLine($"   Content: {content3.Substring(0, Math.Min(300, content3.Length))}");
        
        // Clear auth header
        ClearAuthenticationHeader();
        
        Console.WriteLine($"   EXPECTED: 200 OK or 404 NotFound (user not found in mock)");
        Console.WriteLine($"   ACTUAL: {response3.StatusCode}");
        Console.WriteLine($"   SUCCESS: {(response3.StatusCode != HttpStatusCode.InternalServerError ? "✅ PASS" : "❌ FAIL")}");
    }
    
    [Fact]
    public async Task Debug_NonAuth_Endpoints()
    {
        // Test 4: Non-auth endpoint should work fine
        Console.WriteLine("🔍 TEST 4: Testing non-auth endpoint for comparison");
        
        var loginData = new { email = "test@example.com", password = "password123" };
        var jsonContent = JsonSerializer.Serialize(loginData);
        var httpContent = new StringContent(jsonContent, System.Text.Encoding.UTF8, "application/json");
        
        var response4 = await Client.PostAsync("/api/auth/login", httpContent);
        var content4 = await response4.Content.ReadAsStringAsync();
        
        Console.WriteLine($"   Status: {response4.StatusCode} ({(int)response4.StatusCode})");
        Console.WriteLine($"   Content: {content4.Substring(0, Math.Min(300, content4.Length))}");
        
        Console.WriteLine($"   EXPECTED: 200 OK or 400 BadRequest (not 500)");
        Console.WriteLine($"   ACTUAL: {response4.StatusCode}");
        Console.WriteLine($"   SUCCESS: {(response4.StatusCode != HttpStatusCode.InternalServerError ? "✅ PASS" : "❌ FAIL")}");
    }
}