// <auto-generated />
using GeoLeap.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoLeap.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525153000_AddMobileSubscriptionReplayIndexes")]
    public partial class AddMobileSubscriptionReplayIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
